### ISSUE TITLE
请问怎样设置不构建某个资源

### ISSUE THREAD

**Issue by tanzhihang** [cooliejs/coolie-cli#11]
因为HTML文件有php代码，图片
```php
<img  src="<?php echo $imgSrc; ?>" />
```
因为coolie会处理img的src获取资源。然而这样是获取不了而报错的。请问怎样忽略处理

**Comment by cloudcome** [comment]
可以同指令来忽略这个标签

```
<img  src="<?php echo $imgSrc; ?>"  coolieignore/>
```

官方文档 <https://coolie.ydr.me/introduction/coolie-directive#heading-4>

**Comment by tanzhihang** [comment]
原来加上 coolieignore就可以了，
<img  src="<?php echo $imgSrc; ?>" coolieignore />

**Comment by tanzhihang** [comment]
@cloudcome 谢谢才看到
