### ISSUE TITLE
请问可以自定义js混淆的规则吗？

### ISSUE THREAD

**Issue by tanzhihang** [cooliejs/coolie-cli#12]
比如使用第三方的混淆的插件。有没有接口处理js文件？
----------------------------------------------------
[https://coolie.ydr.me/document/coolie.config.js#heading-4-5](https://coolie.ydr.me/document/coolie.config.js#heading-4-5)
发现minify的配置只有uglify-js的compress，如果我想配置uglify-js的output和mangle怎么做

**Comment by cloudcome** [comment]
建议挺好，后续版本会支持完整的 uglify 配置

**Comment by cloudcome** [comment]
<https://coolie.ydr.me/document/coolie.config.js#heading-4-5>

现已支持
