### ISSUE TITLE
coolie处理php模版的时候出现的问题

### ISSUE THREAD

**Issue by tanzhihang** [cooliejs/coolie-cli#13]
build输出的是
```php
<?php if(isset($item['action']['jumpUrl'])):?>
	<?php 
              if(isset($item['action']['disabled'])) {
		   $tmpStyle = 'style = "background-color:#acacac;cursor:default;"';
	     } else {
		   $tmpStyle = '';
	    }
	?>
	<a class="item-link-btn join" href="javascript:void(0);" PHPkqaronjtfn201811101016349750006 PHPomhyhkjyhd201811101016349750007 a PHPewksesawga20181110101634973000A PHPvzkpauoqka20181110101634973000B data-u="<?=$item['action']['ajaxUrl']?>">
	    <?=$item['action']['text']?>
	</a>
<?php endif;?>
```

在终端打印出sourceMap，找到对应的key和value是对的
`'≤PHPkqaronjtfn201811101016349750006≥': '<?=$tmpStyle?>',`
`'≤PHPomhyhkjyhd201811101016349750007≥': '<?=$item[\'action\'][\'text\']?>',`
`'≤PHPewksesawga20181110101634973000A≥': '<?php endif;?>',`
`'≤PHPvzkpauoqka20181110101634973000B≥': '<?php if(isset($item[\'action\'][\'ajaxUrl\'])):?>',`

**Comment by tanzhihang** [comment]
知道是怎么回事了，是 当php的变量为html标签的属性和属性值时，就不能处理，比如这里的问题：
`
$tmpStyle = 'style = "background-color:#acacac;cursor:default;"';
<a <?=$tmpStyle?>></a>
`
这样的情况就处理不了，非得写成：
`
$tmpStyle = 'background-color:#acacac;cursor:default;';
<a style="<?=$tmpStyle?>"></a>
`

**Comment by cloudcome** [comment]
在处理 HTML 属性时，PHP 的 `<>` 符号影响解析，因为 PHP 的 `<>` 是 HTML 中标签的的符号。为了避免解析错误，请将 PHP 代码写在属性值里。如：

```html
<a style="<?=$tmpStyle?>"></a>
```
