### ISSUE TITLE
关于coolie的若干个问题

### ISSUE THREAD

**Issue by Midqiu** [cooliejs/coolie-cli#3]
##关于源码的问题 
我本意是想把我的项目源码文件夹加到Chrome DevTools的 Workspace 里面。这样我就可以直接在Chrome里面编辑源码，并且使用Chrome调试的强大功能（许多编辑器都做不到的一边Debug一边编辑代码并且Chrome执行编辑后的新代码）。所以我需要一个源码就能直接跑起来的构建机制。在网上找到了coolie。但无论我在coolie-config.js里面配置mode为『CMD』还是『AMD』，调试的时候都是『CommonJS』外面包装成了『AMD』用eval去执行，这样在chrome里面的源码和实际的源码就对应不起来了。这样就浪费了强大的调试功能。能不能开发的时候指定『CMD』或者『AMD』，这样开发过程中，chrome执行的代码就和源码保持一致了。

##打包的问题
 打包后页面上只剩下3个script请求：coolie.js、coolie-config.js和页面的 index.js ,如何把这3个js打包内联到html页面里面？（CSS同理）

##关于编译的问题 
首先作者已经说了暂时不支持ES6的 import之类的模块方式，但是有可能会用到ES6的其他语法，比如说『let』、箭头函数之类的，这些在新版的Chrome浏览器里面都是原生支持的，那么可能会希望开发的时候我在Chrome里面一边开发一边调试，然后到发布的时候我再通过编译工具转换成更多浏览器支持的ES5。 或者其他的比如Typescript之类的，我可以通过其他方式把把ts转成js 文件转好，开发调试的时候保持转换好的js代码和浏览器里面跑的js代码一样（其实就是问题一的问题），我也可以在chrome里面调试，只是这时候Chrome不会热加载Sourcemap文件美发执行重新编译后的JS代码。

**Comment by cloudcome** [comment]
首先，非常感谢你的建议。

## 源码问题
- 虽然是 eval 执行的，但是源代码的行号是不变的，因此可以断点调试。
- mode 模式配置，指的是你的源代码使用的是哪一种模块标准，同时指出 AMD 和 CMD。

## 打包问题
- coolie.js（模块加载器）、coolie-config.js（模块加载器配置文件）、index.js（模块入口文件）三个文件互相独立的，暂时无法合并并且内嵌到页面中。
- CSS 的 link 外链也是无法直接内嵌到页面中，如果想内嵌，可以在开发的时候就这么做。

## 编译问题
- 正如你找到 coolie 的缘由：需要一个源码就能直接跑起来的构建机制。因此 coolie 不会涉及到编译的过程，交付给 coolie 的文件都是处理过后的文件，即原生的 html、css、js 文件。
- 其他过渡语言的文件可以编译之后交给 coolie，如 es6 的 js 文件编译成 es5 的 js 文件、sass 文件编译成 css 文件，等等。

**Comment by Midqiu** [comment]
关于源码的第一个问题，我可能表达的不是很清楚：

常规的调试流程是这样的：
开发者用chrome的Dev Tools 调试代码，比如有一个表单，submit函数里面有这样的代码（假设这一行是第88行）写错了:
```
form.onsubmit=function(){
    var a=1                  // 87行
    console.log(p.nam) //88行 应该为p.name
     .......
}
```
之前的流程是：开发者切换回编辑器，找到第88行代码修改为
```
    console.log(p.name) // 88行
```
，然后切换回浏览器，刷新页面，重新把表单给填写完，然后再点击提交按钮，继续一步步debug submit函数。

chrome浏览器有个workspace的功能，就是把js文件和本地硬盘上的js文件映射起来。然后开发者可以直接在chrome的Dev Tools工具里面编辑修改本地 的 js 源码文件。开发者不需要刷新页面，浏览器也可以跑修改后的js文件（相当于热加载js代码）。

继续拿上面的例子举例，在使用了chrome 了workspace的开发流程如下：
当开发者发现88行代码有问题，直接在Dev Tools里面把88行修改好，然后按ctrl+s，浏览器会自动重新从87行（函数开始的地方）开始debug。而在Dev Tools里面修改的地方会自动同步到源码里面，因为其实修改的就是本地硬盘上的js文件。

**Comment by cloudcome** [comment]
了解了，感谢释疑。

遗憾的是目前使用 eval 执行是无法实现 workspace 的热加载。

**Comment by Midqiu** [comment]
嗯，所以我的建议是，源码支持CMD或者AMD的组织方式，不用eval去实现，而是用script标签的src去实现。

**Comment by cloudcome** [comment]
- COMMONJS 规范没法直接 script src 执行，需要包装一层 define，然后 eval 执行。
- CMD 规范就可以直接 script src 执行。

- coolie 在 1.x 版本只支持 CMD 规范，因此行得通。
- 在 2.x 版本上，为了支持 COMMONJS 规范，CMD 和 COMMONJS 都加上了一层 define。
