### ISSUE TITLE
求教 前后台配合，coolie构建的目录怎么分配

### ISSUE THREAD

**Issue by cd-smallBear** [cooliejs/coolie-cli#5]
### 后台程序使用.net MVC的框架
![](http://p1.bpimg.com/567571/be22d8801dfbe94f.png)
.cshtml文件在图中圈出来的文件夹里面

静态资源全在 wwwroot文件夹里面，
下图是你推荐的开发目录 ，个人经验不足 ，实际用着想不明白。
![](http://p1.bqimg.com/567571/53c9e491a1468375.png)
如果用coolie 构建 ，生成的新目录 对于静态资源还说得过去，但是后台文件夹就不可行了，
这种情况 coolie配合后台是不是就不适合，而.net 在发布的时候可以进行 开发 | 生产 判断输出不同的引用资源，唯一就是要约定好合并或压缩后的文件名，
如果我用coolie去构建 ，（个人喜欢这个高逼格）能配合起来吗？能的话，该怎么做。求云大大给点指导

**Comment by cloudcome** [comment]
下一个 y 版本开放路径相关中间件。

**Comment by cd-smallBear** [comment]
thanks

**Comment by cloudcome** [comment]
构建之前重写路径即可。参考

![image](https://cloud.githubusercontent.com/assets/3362033/19585075/0c4b7258-977c-11e6-9b0d-58e3c9394d42.png)
