### ISSUE TITLE
使用coolie 构建工具的中间件 matchHTML方法，配置的参数匹配结果不正确

### ISSUE THREAD

**Issue by cd-smallBear** [cooliejs/coolie-cli#9]
截图，展示 需要匹配的 标签 
![](http://i1.ciimg.com/1949/ef8d7f90ff992cd9.png)

执行构建 后，
![Markdown](http://i2.tiimg.com/1949/dd7f74fde10ce145.png)
![Markdown](http://i2.tiimg.com/1949/766fa9154519eb79.png)
 发现，如果被匹配的元素存在相同标签名的子元素，都无法被匹配到。（有粗下划线的匹配了，红框起来的DIV 没有被匹配）

**Comment by cloudcome** [comment]
感谢反馈，已解决 v2.2.3
